#!/bin/bash

#####################################
#
# Date:    07-09-2019
# Author:  12oClocker
# License: GNU GPL v2 (see License.txt), GNU GPL v3 or proprietary (CommercialLicense.txt)
#
#####################################
#
# this script will put the cycle count in front of each opcode in the lss file
# if an opcode has more than one possible cycle count, then it may read 123_cpse, meaning it can be 1,2, or 3 cycles
#

#change the "out_attiny1614" to whatever file you want to count opcodes on
FILE=./out_attiny1614/main.lss

OPT="  s/	push/	1_push/g;"
OPT+=" s/	add/	1_add/g;"
OPT+=" s/	adc/	1_adc/g;"
OPT+=" s/	adiw/	2_adiw/g;"
OPT+=" s/	sub/	1_sub/g;"
OPT+=" s/	subi/	1_subi/g;"
OPT+=" s/	sbc/	1_sbc/g;"
OPT+=" s/	sbci/	1_sbci/g;"
OPT+=" s/	sbiw/	2_sbiw/g;"
OPT+=" s/	and/	1_and/g;"
OPT+=" s/	andi/	1_andi/g;"
OPT+=" s/	or/	1_or/g;"
OPT+=" s/	ori/	1_ori/g;"
OPT+=" s/	eor/	1_eor/g;"
OPT+=" s/	com/	1_com/g;"
OPT+=" s/	neg/	1_neg/g;"
OPT+=" s/	sbr/	1_sbr/g;"
OPT+=" s/	cbr/	1_cbr/g;"
OPT+=" s/	inc/	1_inc/g;"
OPT+=" s/	dec/	1_dec/g;"
OPT+=" s/	tst/	1_tst/g;"
OPT+=" s/	clr/	1_clr/g;"
OPT+=" s/	ser/	1_ser/g;"
OPT+=" s/	mul/	2_mul/g;"
OPT+=" s/	muls/	2_muls/g;"
OPT+=" s/	mulsu/	2_mulsu/g;"
OPT+=" s/	fmul/	2_fmul/g;"
OPT+=" s/	fmuls/	2_fmuls/g;"
OPT+=" s/	fmulsu/	2_fmulsu/g;"
OPT+=" s/	rjmp/	2_rjmp/g;"
OPT+=" s/	ijmp/	2_ijmp/g;"
OPT+=" s/	jmp/	3_jmp/g;"
OPT+=" s/	rcall/	23_rcall/g;"
OPT+=" s/	icall/	23_icall/g;"
OPT+=" s/	call/	34_call/g;"
OPT+=" s/	ret/	45_ret/g;"
OPT+=" s/	reti/	45_reti/g;"
OPT+=" s/	cpse/	123_cpse/g;"
OPT+=" s/	cp/	1_cp/g;"
OPT+=" s/	cpc/	1_cpc/g;"
OPT+=" s/	cpi/	1_cpi/g;"
OPT+=" s/	sbrc/	123_sbrc/g;"
OPT+=" s/	sbrs/	123_sbrs/g;"
OPT+=" s/	sbic/	123_sbic/g;"
OPT+=" s/	sbis/	123_sbis/g;"
OPT+=" s/	brbs/	12_brbs/g;"
OPT+=" s/	brbc/	12_brbc/g;"
OPT+=" s/	breq/	12_breq/g;"
OPT+=" s/	brne/	12_brne/g;"
OPT+=" s/	brcs/	12_brcs/g;"
OPT+=" s/	brcc/	12_brcc/g;"
OPT+=" s/	brsh/	12_brsh/g;"
OPT+=" s/	brlo/	12_brlo/g;"
OPT+=" s/	brmi/	12_brmi/g;"
OPT+=" s/	brpl/	12_brpl/g;"
OPT+=" s/	brge/	12_brge/g;"
OPT+=" s/	brlt/	12_brlt/g;"
OPT+=" s/	brhs/	12_brhs/g;"
OPT+=" s/	brhc/	12_brhc/g;"
OPT+=" s/	brts/	12_brts/g;"
OPT+=" s/	brtc/	12_brtc/g;"
OPT+=" s/	brvs/	12_brvs/g;"
OPT+=" s/	brvc/	12_brvc/g;"
OPT+=" s/	brie/	12_brie/g;"
OPT+=" s/	brid/	12_brid/g;"
OPT+=" s/	mov/	1_mov/g;"
OPT+=" s/	movw/	1_movw/g;"
OPT+=" s/	ldi/	1_ldi/g;"
OPT+=" s/	lds/	34_lds/g;"
OPT+=" s/	ld/	23_ld/g;"
OPT+=" s/	ldd/	23_ldd/g;"
OPT+=" s/	sts/	23_sts/g;"
OPT+=" s/	st/	12_st/g;"
OPT+=" s/	std/	12_std/g;"
OPT+=" s/	lpm/	3_lpm/g;"
OPT+=" s/	in/	1_in/g;"
OPT+=" s/	out/	1_out/g;"
OPT+=" s/	push/	1_push/g;"
OPT+=" s/	pop/	2_pop/g;"
OPT+=" s/	lsl/	1_lsl/g;"
OPT+=" s/	lsr/	1_lsr/g;"
OPT+=" s/	rol/	1_rol/g;"
OPT+=" s/	ror/	1_ror/g;"
OPT+=" s/	asr/	1_asr/g;"
OPT+=" s/	swap/	1_swap/g;"
OPT+=" s/	sbi/	1_sbi/g;"
OPT+=" s/	cbi/	1_cbi/g;"
OPT+=" s/	bst/	1_bst/g;"
OPT+=" s/	bld/	1_bld/g;"
OPT+=" s/	bset/	1_bset/g;"
OPT+=" s/	bclr/	1_bclr/g;"
OPT+=" s/	sec/	1_sec/g;"
OPT+=" s/	clc/	1_clc/g;"
OPT+=" s/	sen/	1_sen/g;"
OPT+=" s/	cln/	1_cln/g;"
OPT+=" s/	sez/	1_sez/g;"
OPT+=" s/	clz/	1_clz/g;"
OPT+=" s/	sei/	1_sei/g;"
OPT+=" s/	cli/	1_cli/g;"
OPT+=" s/	ses/	1_ses/g;"
OPT+=" s/	cls/	1_cls/g;"
OPT+=" s/	sev/	1_sev/g;"
OPT+=" s/	clv/	1_clv/g;"
OPT+=" s/	set/	1_set/g;"
OPT+=" s/	clt/	1_clt/g;"
OPT+=" s/	seh/	1_seh/g;"
OPT+=" s/	clh/	1_clh/g;"
OPT+=" s/	break/	1_break/g;"
OPT+=" s/	nop/	1_nop/g;"
OPT+=" s/	sleep/	1_sleep/g;"
OPT+=" s/	wdt/	1_wdt/g" # no semicolon on last command

sed -i "$OPT" $FILE
